import { SITE } from '@/config/site'

export const base = `https://${SITE.domain}`
export const url = (path = '/') => `${base}${path.startsWith('/') ? '' : '/'}${path}`

// entity-encode an email so it never appears as plaintext (incl. JSON-LD)
export const encEmail = (e) =>
  e.replace(/[A-Za-z@.]/g, (c) => `&#${c.charCodeAt(0)};`)

// Branded 1200x630 PNG generated by scripts/gen-og.mjs. Used whenever a page
// doesn't supply its own image — SVG must never be an og:image (most social and
// AI unfurlers don't render it).
export const OG_DEFAULT = url('/og/default.png')

// Trim to <=158 chars on a word boundary (never mid-word), keeping trailing
// punctuation tidy. A description written within budget passes through untouched.
function clampDesc(s) {
  const t = (s || '').trim()
  if (t.length <= 158) return t
  return t.slice(0, 158).replace(/\s+\S*$/, '').replace(/[\s,;:—-]+$/, '') + '…'
}

export function buildMetadata({ title, description, path = '/', type = 'website', image, robots, absoluteTitle }) {
  const canonical = url(path)
  const desc = clampDesc(description || SITE.description)
  const ogImage = image || OG_DEFAULT
  // Next's typed metadata only accepts a subset of OG types; map product→website.
  const ogType = type === 'product' ? 'website' : type
  const meta = {
    // absoluteTitle bypasses the layout "%s | VoltTrack" template (used by /parts/
    // pages, whose titles already end in "| VoltTrack Parts").
    title: absoluteTitle ? { absolute: absoluteTitle } : title,
    description: desc,
    alternates: { canonical },
    openGraph: {
      type: ogType,
      siteName: SITE.name,
      title,
      description: desc,
      url: canonical,
      images: [ogImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: desc,
      images: [ogImage],
    },
  }
  if (robots) meta.robots = robots
  // Search-engine verification lives once in the root layout metadata (site-wide),
  // not per page — avoids duplicate verification <meta> tags.
  return meta
}

export function JsonLd({ data }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  )
}
